name: Build and push image to Docker hub

on:
  push:
    branches: [ main ]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to world
        run: echo "Hello World"

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Git commit SHA
        id: vars
        run: echo "GIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jenkins:latest
            ${{ secrets.DOCKER_USERNAME }}/jenkins:${{ steps.vars.outputs.GIT_SHA }}
